repos:

# Prevent commits to main/master
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'main', '--branch', 'master']
      fail_fast: true

# Make sure to run isort before black formatting, because black will
# reformat the imports differently then isort reformats them.
- repo: https://github.com/PyCQA/isort
  rev: 5.6.4
  hooks:
  - id: isort
    args: [--filter-files]
    files: \.py$

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: detect-private-key
  - id: check-added-large-files

# Flake8 checks are last, as this checks if everything is in order.
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
      - id: flake8
        additional_dependencies:
          - Flake8-pyproject
          - flake8-builtins
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-broken-line
          - flake8-quotes
          - flake8-rst-docstrings
          - flake8-docstrings
          - pep8-naming
          - importlib-metadata<4.3
