name: default
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.8"
        poetry-version:
          - "1.3.1"
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - uses: snok/install-poetry@v1
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install libasound2 (for rtmidi)
        run: sudo apt-get install libasound2-dev

      - name: Print the poetry version to make sure it is installed
        run: poetry --version

      - name: Setup the dev environment
        run: make install

      - name: Run Unittests
        run: make test

      - name: Build the package
        run: make build
