name: default
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-integration:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version:
          - "3.8"
        poetry-version:
          - "1.3.1"
        os:
          - ubuntu-latest
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - uses: snok/install-poetry@v1
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - run: poetry --version

      - run: make install

      - run: make test

      - run: make build
